### ISSUE TITLE
Better parse the ${} value in Checkstyle configuration

### ISSUE THREAD

**Issue by doppelreim** [jdneo/vscode-checkstyle#107]
Hi there,

I have set `checkstyle.configurationFile` to point to the project's `checkstyle.xml`.

It contains the following:
```
<module name="SuppressionFilter">
    <property name="file" value="${suppressionFile}" default="suppression.xml"/>
</module>
```

But that crashes the plugin with this in the output:
```
Checkstyle Error: - 'Command failed with exit code: 254. Stderr: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: suppression.xml
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:457)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
```

The `suppression.xml` is next to `checkstyle.xml` in the file-system.
When I put the absolute path to the `suppression.xml` into the `default`-attribute, then it works. But that would not be portable.

Would it be possible to support this use-case? Maybe with a new plugin-config?
Or should it already be possible?

(I am not very familiar with checkstyle, so maybe I mixed some stuff up here - sorry, if that's the case)

**Comment by jdneo** [comment]
Hi @doppelreim ,

What you are doing is correct. Actually I asked the same question to the checkstyle team: https://github.com/checkstyle/checkstyle/issues/5515

The answer is that we need to set the value in the `<property>`. Just as you did.

But for the extension we can still improve this. By telling users to give the correct value if we find there is `${...}` pattern in the property.

I'll work on a fix for this.

**Comment by jdneo** [comment]
Closing this issue since the extension has been rewritten from `1.0.0`, the core mechanism has been changed.

Users now can set the property in the `settings.json`. Meanwhile the keywords `${workspaceFolder}` is supported to make sure it will be portable.
