### ISSUE TITLE
Exclude dirs/files

### ISSUE THREAD

**Issue by landau** [jdneo/vscode-checkstyle#115]
Thanks for the great plugin! I have generated code that I would like the plugin to ignore, specifically classes generated from `protoc`. These don't and shouldn't be checked. Can you please add an option to ignore directories and/or files?

Thanks for your time. :)

**Comment by jdneo** [comment]
@landau Thank you for your feedback.

I think the `SuppressionFilter` may help you with this problem. It's a part of the configuration of Checkstyle. To suppress all checks in generated sources:

```xml
<suppress checks=".*" files="com[\\/]mycompany[\\/]app[\\/]gen[\\/]"/>
```

More details can be found here: http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter

**Comment by landau** [comment]
Thanks!!
