### ISSUE TITLE
Can't show correct validation hint when entering version number "8.00"

### ISSUE THREAD

**Issue by sallyur** [jdneo/vscode-checkstyle#116]
It is not a regression issue, it is also repro in marketplace version.
1.	Open command palatte
2.	Find and select Checkstyle: Set Version
3.	Choosing enter a version number, type "8.00" 

Result:
	Can't show correct validation hint when entering version number "8.00", but can show hint the version number is invalid
![image](https://user-images.githubusercontent.com/28860891/40532784-2f6a07dc-6033-11e8-8e65-84f3f3102fd4.png)
![image](https://user-images.githubusercontent.com/28860891/40532792-39601560-6033-11e8-97af-df3354119037.png)

**Comment by jdneo** [comment]
Closing this issue since the extension has been rewritten from `1.0.0`, the core mechanism has been changed.
