### ISSUE TITLE
 Trigger clean checkstyle violation, a check icon change to a pencil icon

### ISSUE THREAD

**Issue by sallyur** [jdneo/vscode-checkstyle#117]
1. A check icon show at the right-bottom corner
2. Trigger clean checkstyle violation

Result:
Checkstyle status icon change to a pencil icon

Expect:
A check icon show at the right-bottom corner

**Comment by jdneo** [comment]
Closing this issue since the extension has been rewritten from `1.0.0`, the core mechanism has been changed.
