### ISSUE TITLE
The current behavior of triggering Check Code through file explorer is unfriendly

### ISSUE THREAD

**Issue by sallyur** [jdneo/vscode-checkstyle#127]
Now the status bar only shows the current active file check results. When triggering Check Code through file explorer, test results for unopened files cannot be shown in the states bar.

Expected:
When triggering Check Code through file explorer, open the file and display the results in the states bar.

**Comment by jdneo** [comment]
Closing this issue since the extension has been rewritten from `1.0.0`, the core mechanism has been changed.
