### ISSUE TITLE
The link of "CHANGELOG" which is in the Details tab of this plugin in marketplace is invalid

### ISSUE THREAD

**Issue by JanusWu** [jdneo/vscode-checkstyle#136]
The link of "[CHANGELOG](https://github.com/jdneo/vscode-checkstyle/blob/master/CHANGELOG.md)" in below screenshot is invalid. It's a 404 page.

![image](https://user-images.githubusercontent.com/17060520/42084088-554b68ea-7bbf-11e8-8675-7f205538f88a.png)

**Comment by jdneo** [comment]
Fixed in #125
