### ISSUE TITLE
0.5.2 Endgame

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-checkstyle#139]
## Build @jdneo

- [x] Bump version to 0.5.2
- [x] Update Readme.md
- [x] Update changelog
- [x] Merge develop into master

## Test @bsaby 

- [x] Run [Test Plan](https://github.com/jdneo/vscode-checkstyle/wiki/Test-Plan)

## Release @jdneo
- [x] Add tag
- [x] Release to marketplace

**Comment by sallyur** [comment]
### Run Test Plan

Build: 12
Open bug: #140
Test result:

Test   case | Win10   x64 | Mac | Issues
-- | -- | -- | --
Configurations | VScode   1.25.1   Jdk1.8.0_171 | VSCode:1.25.1   Jdk1.8.0_161 |  
Clean   install | Pass | Pass |  
Update | Pass | Pass |  
Uninstall | Pass | Pass |  
Can set checkstyle version | Pass | Pass |  
Can set checkstyle configuration | Pass | Pass |  
Can turn on/off autocheck | Pass | Pass |  
Can set Checkstyle property | Pass | Pass | #140
Can trigger check code with checkstyle | Pass | Pass |  
Can trigger clean checkstyle violation | Pass | Pass |  
Status Bar | Pass | Pass |  
Telemetry | Pass | Pass |
