### ISSUE TITLE
Can not read property 'trim' of undefined

### ISSUE THREAD

**Issue by sallyur** [jdneo/vscode-checkstyle#140]
Build: master 12

Repro steps:

1. Open command palatte  
2. Find and select "Checkstyle: Set Configuration" 
3. Choose browse and given a customized configuration file  
4. Selecting application or workspace  
5. Set property file  
6. Clear the property file and save  
7. Open command palatte  
8. Find and select "Checkstyle: Set Configuration"  
9. Choose browse and given a customized configuration file  
10. Selecting application or workspace  

Result: Can not read property 'trim' of undefined
![image](https://user-images.githubusercontent.com/28860891/43511329-b3608190-95aa-11e8-8b36-57da61b0a4c2.png)

**Comment by jdneo** [comment]
Fixed in https://github.com/jdneo/vscode-checkstyle/commit/bffcc035d1fc80e984cd439cf4a09e5f804db1e5
