### ISSUE TITLE
[Error] spawn checkstyle ENOENT

### ISSUE THREAD

**Issue by Drakmyth** [jdneo/vscode-checkstyle#142]
After installing this extension and setting autocheck to true, saving any change to any file causes

`[Error - 11:22:27 AM] spawn checkstyle ENOENT`

to appear in the Checkstyle output. Each further change to any file in the project will repeat the same error with updated timestamps. This also forces the Checkstyle output tab into focus, making it very frustrating if that panel is docked with any other (such as the problems tab, which it is by default, for example).

Extension version 0.5.2
VSCode version 1.26.0
Checkstyle version 6.18

**Comment by Drakmyth** [comment]
All I see in the console in developer tools is

`INFO no standard startup: panel is active
INFO No grammar found for scope text.html.javadoc`

**Comment by jdneo** [comment]
Hmm, seems something related with the path.

Not sure if there a way that I can repro this on my side. Do you have any steps that can help me to repro this?

**Comment by Drakmyth** [comment]
Don't really have repro steps, but I uninstalled and reinstalled the extension, and now it seems to be working fine. I'm going to go ahead and close this since it looks like it was just something in my local environment.
