### ISSUE TITLE
Do we need to install anything in order to use this extension

### ISSUE THREAD

**Issue by HaoyangFan** [jdneo/vscode-checkstyle#143]
Hi, do we need to install anything besides simply installing this extension on VSCode? A similar extension on atom requires to install something from command-line, so I am wondering if it is the same for this extension

Thanks

**Comment by jdneo** [comment]
Nothing else is needed. You can filling the checkstyle version and the extension will automatically download the executable jar for you.

**Comment by jdneo** [comment]
Closing because the issue has been inactive for a long time.
