### ISSUE TITLE
The file is saved in the editor will not be checked after only modify checkstyle.xml

### ISSUE THREAD

**Issue by ZhengJun003** [jdneo/vscode-checkstyle#151]
**Reproduce:**

1. Open a file which has some style problems in the editor, let extension check it.
2. Go to checkstyle.xml comment the check and save it.
3. Return to the previous file and save it.
4. Error occurs, the extension doesn't check the code, and the violations problems still show in problem view.

**Environments**

* OS: Windows 10
* VS Code version: 1.31.1
* Extension version; Build 18

**Comment by jdneo** [comment]
@ZhengJun003 Fixed

**Comment by ZhengJun003** [comment]
Verify in Build withSign/4, it's fixed.
