### ISSUE TITLE
Errors not disappear after user applying the quick fixes and saving the file if autocheck is false

### ISSUE THREAD

**Issue by ZhengJun003** [jdneo/vscode-checkstyle#157]
**Description:**

java.checkstyle.autocheck is false, Errors do not disappear after user applying the quick fixes and saving the file

**Environments**

* OS: Windows 10/OS X
* VS Code version: 1.31.1
* Extension version; Build withsign/4

**Comment by jdneo** [comment]
It's by design since `autocheck` is false. The extension won't check the code on the save event.
