### ISSUE TITLE
Configuration file with relative path (instead of absolute) for workspace settings

### ISSUE THREAD

**Issue by bennettdams** [jdneo/vscode-checkstyle#174]
It would be nice have the possiblity of setting the configuration file with a relative path.

Right now I have one folder to hold "global" configurations like Checkstyle, Prettier, TSLint, etc. that gets used by several different applications. All settings are inside the workbench config file (`*.code-workspace`).

```
    -- hub-repo
       my-workspace.code-workspace
       |-- dev-settings
          |--- Checkstyle
               |--- checkstyle.xml
          |--- ...
       |-- app1
       |-- app2
       |-- ...
```

We are using this workspace file with multiple developers as a baseline for the development environment.

For example, TSLint or Prettier allow relative paths:

`"tslint.configFile": "..\\..\\dev-settings\\TSLint\\tslint.json",`

The equivalent Checkstyle option could look like this:

`"java.checkstyle.configuration": "..\\..\\Checkstyle\\checkstyle.xml"`

...instead of

`"java.checkstyle.configuration": "C:\\Code\\.....\\dev-settings\\Checkstyle\\checkstyle.xml"`

**Comment by jdneo** [comment]
Hi @bennettdams, 

Actually, you can use the reserved words `${workspaceFolder}` to achieve that. For example `${workspaceFolder}/../../Checkstyle\\checkstyle.xml`, something like that.

> More details can be found [here](https://github.com/jdneo/vscode-checkstyle#settings)

**Comment by bennettdams** [comment]
Hey @jdneo, 

it does not seem to work. even with defined workspace folder names like so:

```
{
    "folders": [
        {
            "name": "App 1",
            "path": "..\\app-1"
        },
        {
            "name": "App 2",
            "path": "..\\app-2"
        },
        {
            "name": "Development settings",
            "path": "..\\dev-settings"
        }
    ],
    "settings": {
        ...
        // JAVA
        "java.configuration.updateBuildConfiguration": "interactive",
        "java.checkstyle.configuration": "${workspaceFolder:Development settings}\\Checkstyle\\checkstyle.xml"
        ...
        // OR "java.checkstyle.configuration": "${workspaceFolder}\\Checkstyle\\checkstyle.xml"
    },
   ...
}

```

Unfortunately, even with VS Code's developer tools, the only error message is `workbench.main.js:2365 The Checkstyle configuration file does not exist. Please make sure it is set correctly.`.

Is there any easy way to see the path that the Checkstyle extension is looking for? I'm not sure if `$[workspaceFolder}` actually gets resolved in my `*.code-workspace` file.

**Comment by jdneo** [comment]
Hmm, honestly, I'm confused now.

Would you mind to create a repo which has the project structure to help me understand the issue?

You can remove all the code files just leave the structure there.

**Comment by bennettdams** [comment]
I can provide a repository in a few hours.

For now I modified the code and printed out the `configurationPath`, which shows that `${workspaceFolder}` actually does not get resolved, it is just part of the string.
https://github.com/jdneo/vscode-checkstyle/blob/ab8509a8d6906c06dea9b91fe42682178e46693a/src/commands/check.ts#L36-L39

Here is an PR to add the configuration path to the error message: #180

**Comment by jdneo** [comment]
That's wired. It should be resolved. See:

https://github.com/jdneo/vscode-checkstyle/blob/master/src/commands/check.ts#L31

and

https://github.com/jdneo/vscode-checkstyle/blob/master/src/utils/settingUtils.ts#L7-L9

**Comment by bennettdams** [comment]
@jdneo There's actually a bug in the code:

https://github.com/jdneo/vscode-checkstyle/blob/27f4d14c962f9f7c091640ba060b3dba328b8374/src/utils/settingUtils.ts#L28

`const workspaceRegexp: RegExp = /\$\{workspacefolder\}/i;`

should be

`const workspaceRegexp: RegExp = /\$\{workspaceFolder\}/i;`  
(with capital F)

Here is a PR with the fixed regex:   #180

This fixed the path for me, as the variable gets resolved.

By the way: Right now this does **not** support scoped variables per workspace folder:
https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

..but this is another story.

**Comment by bennettdams** [comment]
I completely reinstalled VS Code and now `${workspaceFolder}` gets resolved.
e. g.  `"java.checkstyle.configuration": "${workspaceFolder}\\..\\dev-settings\\Checkstyle\\checkstyle.xml"`

[Scoped variables for multi-root workspaces](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder) are not supported with the `resolveVariables` function, but that's another story. 

https://github.com/jdneo/vscode-checkstyle/blob/27f4d14c962f9f7c091640ba060b3dba328b8374/src/utils/settingUtils.ts#L28-L38

**Comment by bennettdams** [comment]
I completely reinstalled VS Code and now `${workspaceFolder}` gets resolved.
e. g.  `"java.checkstyle.configuration": "${workspaceFolder}\\..\\dev-settings\\Checkstyle\\checkstyle.xml"`

[Scoped variables for multi-root workspaces](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder) are not supported with the `resolveVariables` function, but that's another story. 

https://github.com/jdneo/vscode-checkstyle/blob/27f4d14c962f9f7c091640ba060b3dba328b8374/src/utils/settingUtils.ts#L28-L38 

Thanks, @jdneo.
