### ISSUE TITLE
Support live linting experience

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-checkstyle#175]
Currently, the extension will only update the check result on the saving event. It will be better if the extension can check the code lively. Just as what the `tslint` extension does

**Comment by Vigilans** [comment]
Here is the proposal.

## Target

The only available API to launch a checkstyle diagnostic is [`process(List<File> files)`](https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java#L206), which requires a physical file on the disk. This directly prevent us from doing live linting with the editing unsaved file.

Referencing idea plugin, it encapsulate a [`ScannableFile`](https://github.com/jshiell/checkstyle-idea/blob/5a991d5ab67e9343f6697ca214200fc5f2b41f6c/src/main/java/org/infernus/idea/checkstyle/checker/ScannableFile.java#L66) to either point to a physical file or a temp file, and uses a uniform interface [`ScanableFile::getFile`](https://github.com/jshiell/checkstyle-idea/blob/master/src/csaccess/java/org/infernus/idea/checkstyle/service/cmd/OpScan.java#L65) to represent a physical file path. We should also manage to utilize the temp file for the diagnostic of unsaved documents. 

Thus the proposal's main targets is:
* Utilize a synchronizer to sync the editing unsaved document with a temp file.
* Use the unedited document or the synced temp file for in-time linting.

## Proposed Mechanism

### DiagnosticManager

A controller responsible for receiving document events and arrange diagnostic requests.

### SyncedFile

A uniform class to encapsulate a document. It provides a `syncUri` property to point to the temp file or the original document.

### FileSynchronizer

A controller responsible for receiving request from `SyncedFile` and sync the doc with the temp file.

This structure is similar with Typescript extension's [`BufferSyncSupport`](https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/features/bufferSyncSupport.ts#L42).  But differs with it in that  `FileSynchronizer` syncs the editing doc with temp file by file IO, where `BufferSynchronizer` syncs with the memory in remote server by json-rpc request.

## Walk Through

### Manager Side: Receiving event
1. `DiagnosticManager` receives an event, e.g. `onDidDocumentChangeEvent`.
2. The manager finds the corresponding `SyncedFile` according to the event.
3. The manager forwards the event to `SyncedFile` as a corresponding api call (`file.change(...)`). 
4. The manager requests a new diagnostic (live-linting).

### Synced File side
1. The synced file does some document property checking (is dirty or not).
2. The synced file as file synchronizer request.

### File Synchronizer Side
1. On receiving request: put the request (open, change, or close) to pending queue.
2. On flushing: send out all the real IO requests in the pending queue, then clear the queue.

### Manager Side: Sending request
1. Before every actual diagnostic request, flush the synchronizer to sync the temp file with current document.
2. Send the document to checkstyle server. Currently we only support sending one document per check, but will evolve to batch processing in subsequent works.

## IO Thrashing Prevention

One critical part to improve the performance is to reduce IO requests to prevent thrashing. I come up with several mechanisms to deal with it:
* Delayed diagnostic request.
* Merged IO request.

## Parse error handling

Doing live linting often results in editing document with parse error. In this situation checkstyle will throw `MismatchedTokenException`(for invalid syntax token) or `TokenStreamRecognitionException`(for invalid escape before a token, such as `\int`).

**Comment by jdneo** [comment]
Closed since it has been addressed in #185 & #186
