### ISSUE TITLE
Allow specifying checkstyle config as a URL

### ISSUE THREAD

**Issue by bbeaudreault** [jdneo/vscode-checkstyle#181]
At my company we have a team which manages our checkstyle rules, and they put it in our internal github. We can then configure intellij to point at the raw unauthed URL, and it picks up any changes to the config each time it starts. I'm so sick of intellij's bloat and am trying out vscode. Any chance your plugin can be updated to work with a URL?

**Comment by jdneo** [comment]
Thanks @bbeaudreault for the feedback. Just for clarification, do you mean this setting?

![image](https://user-images.githubusercontent.com/6193897/59889881-12097a80-9401-11e9-9f62-f44c5d5445a7.png)

**Comment by bbeaudreault** [comment]
Yes, that's the one!

**Comment by bbeaudreault** [comment]
Thanks!

**Comment by jdneo** [comment]
@bbeaudreault The new version of checkstyle extension 1.0.3 has been released. Please have a try!
