### ISSUE TITLE
java.checkstyle.configuration with url pointing to google checks does not work

### ISSUE THREAD

**Issue by manastalukdar** [jdneo/vscode-checkstyle#188]
CheckStyle: `1.0.3`

VSCode and Platform:

```
Version: 1.37.0-insider (user setup)
Commit: 6d82826e990407364d5c829b73602a19ecdf7d00
Date: 2019-07-26T05:37:26.606Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

As per the documentation `java.checkstyle.configuration` supports URLs.

Setting:

```text
"java.checkstyle.configuration": "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml"
```

This results in the following CheckStyle error (formatted for readability):

```text
{"message":"cannot initialize module TreeWalker - cannot initialize module InvalidJavadocPosition - Unable to instantiate 'InvalidJavadocPosition' class, it is also not possible to instantiate it as .InvalidJavadocPosition, InvalidJavadocPositionCheck, .InvalidJavadocPositionCheck.
Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly."}
```

**Comment by jdneo** [comment]
Seems that the embedded checkstyle version needs to be upgraded.

**Comment by jdneo** [comment]
Hi @manastalukdar,

The root cause is that CheckStyle has some breaking changes from `8.18` to `8.23`. The workaround is to change the URL to: `https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.18/src/main/resources/google_checks.xml`

**Comment by manastalukdar** [comment]
Thanks. Is this extension going to support checkstyle v8.23 at some point?

**Comment by jdneo** [comment]
@manastalukdar I'm still considering the best way to solve this problem. Since using `8.23` will break some previous rules as well.

A better solution might be allowing users to config the version by himself, just as this issue says: https://github.com/jdneo/vscode-checkstyle/issues/172

**Comment by jdneo** [comment]
@manastalukdar we have added the support to dynamically select Checkstyle version. Please wait for the next release, which will be shipped recently.
