### ISSUE TITLE
Cannot synchronize checkstyle config file changes in real time

### ISSUE THREAD

**Issue by ZhengJun003** [jdneo/vscode-checkstyle#203]
**Description:**
When a user changes the config in checkstyle.xml, the plugin can't sync in real time. User should reload window or restart vscode to enable the changed config.
This is a regression issue, can synchronize checkstyle config file changes in real time in the previous version.

**Reproduce Step:**
1. Clone and using vscode open https://github.com/Microsoft/todo-app-java-on-azure.git
2. Set the Checkstyle configuration file in the file explorer by Select Set the Checkstyle
3. Right-click a folder, selecting Check Code with Checkstyle
4. Verity checkstyle diagnostics in problem panel and comment a config in checkstyle config file
5. Verify the commented config can still diagnostic
6. Execute Developer: Reload Window in the command palette
7. The commented config can not diagnostic

**Environments:**

- OS: Windows 10
- VS Code version: 1.36.1
- Extension version; 1.1.0

**Comment by Vigilans** [comment]
Now we should listen to the file change of checkstyle xml. When the config is updated, resync with the checkstyle server.

**Comment by jdneo** [comment]
Thanks @ZhengJun003. The issue has been fixed. Could you please help verify if this has been addressed?

**Comment by ZhengJun003** [comment]
Test failed, this issue still exists

Cannot check UpperEll and still check EmptyStatement
![image](https://user-images.githubusercontent.com/41051257/62603141-daf71600-b927-11e9-8e92-c519c0b6ef82.png)

**Comment by ZhengJun003** [comment]
Test Pass
Version: 1.1.0
