### ISSUE TITLE
Upgrade embedded Checkstyle version to 8.23

### ISSUE THREAD

**Issue by simahao** [jdneo/vscode-checkstyle#208]
Plugin use checkstyle(8.18 version),what is your plan for upgrading to lastest(8.23 version)?
Or tell me how to upgrade to 8.23 by myself. 3ks.

**Comment by jdneo** [comment]
If you want to upgrade by yourself. Please try:

1. Download checkstyle 8.23: https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.23/checkstyle-8.23-all.jar

2. replace the jar at: `$HOME\.vscode\extensions\shengchen.vscode-checkstyle-1.1.0\server\com.shengchen.checkstyle.runner-1.1.0.jar\lib\checkstyle-8.18-all.jar`. **But keep the jar name `checkstyle-8.18-all.jar`**

**Comment by simahao** [comment]
I tried your way before opening this issue,but there were some errors in the output console.
1.If u replace the checkstyle-8.18-all.jar with checkstyle-8.23-all.jar,and keep the jar name checkstyle-8.18.-all.jar,error message like below.
![image](https://user-images.githubusercontent.com/4537287/63075799-7d854980-bf65-11e9-9b32-566882779245.png)
But in fact,that class exist.
![image](https://user-images.githubusercontent.com/4537287/63075918-d9e86900-bf65-11e9-8863-0a5e5bcee8eb.png)


2..If u replace the checkstyle-8.18-all.jar with checkstyle-8.23-all.jar,but not change jar name,error message like below.
![image](https://user-images.githubusercontent.com/4537287/63075956-fe444580-bf65-11e9-815f-95e55862796a.png)

**Comment by jdneo** [comment]
The jar name should be changed to `checkstyle-8.18-all.jar`.

You can clean the osgi cache and try again:
- Close your VS Code sessions
- Remove `$HOME/.vscode/extensions/redhat.java-*/server/config_win/org.eclipse.osgi`
- Start VS Code

Note: the folder name `config_win` depends on your OS

**Comment by simahao** [comment]
3ks，it worked.

**Comment by jdneo** [comment]
@simahao we have added the support to dynamically select Checkstyle version. Please wait for the next release, which will be shipped recently.

**Comment by simahao** [comment]
I updated to 1.3.0 just now, appreciate for your  work.I see download link is [https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${version}/checkstyle-${version}-all.jar], but this link is so slow, downloading process was hung, i dont know if there is quick link for china?

**Comment by jdneo** [comment]
Hi @simahao,

Since the Checkstyle hosts there binaries on GitHub, so that is the only place that the extension will download the jar from.

But we may add support to enable the user to specify the local jar file in the future.

**Comment by simahao** [comment]
yes, maybe set local jar path in settings is convenient way.
