### ISSUE TITLE
The setting will not be saved to settings.json when use command Checkstyle: Set the Checkstyle Configuration File

### ISSUE THREAD

**Issue by ZhengJun003** [jdneo/vscode-checkstyle#221]
**Environments:**
```
OS: Windows 10
VS Code version: 1.37.1
Extension version; 1.2.0
```
**Reproduce Steps:**

1. Open a java project, e.g. https://github.com/Microsoft/todo-app-java-on-azure.git
2. Set the Checkstyle configuration file through the VS Code command `Checkstyle: Set the Checkstyle Configuration File`
3. Click Google's Style or any other options
4. Verify workspace folder setting

**Actual Behavior:**

The setting will not be saved to settings.json when use command `Checkstyle: Set the Checkstyle Configuration File`.

![image](https://user-images.githubusercontent.com/41051257/64092663-45b13b00-cd88-11e9-987a-fb965b64158f.png)

**Comment by Vigilans** [comment]
Could you provide the log in Checkstyle channel?
The testcase worked fine in mac; I'm going on to test it in Windows.

**Comment by ZhengJun003** [comment]
Works after a moment, this issue is caused by the plugin is not ready
