### ISSUE TITLE
support checksytle version config@1.3.0

### ISSUE THREAD

**Issue by simahao** [jdneo/vscode-checkstyle#252]
I have updated to 1.3.0,i select 8.24 and download jar file when plugin prompt,but when i restart vscode, plugin prompt select checkstyle version again.（i set defalut checkstyle version to 8.24 in my setting）

**Comment by Vigilans** [comment]
What is the prompt shown & where is your version setting set (user settings or workspace settings)?

**Comment by jdneo** [comment]
@simahao More information is preferred to help doagnostic, like screenshot, logs, etc...

And please make sure your configuration is compatible with 8.24

**Comment by simahao** [comment]
hi guys, thanks for your response, i figured out this problem.I use checkstyle plugin and my project use maven-checksytle-plugin, maven-checkstyle-plugin depend on checkstyle on 8.19 default, after update to 8.24, all works,thanks for your works.

**Comment by Vigilans** [comment]
@simahao Thanks! Your investigation really shows that vscode should automatically sync with maven/gradle project setting if possible. This feature may be done in subsequent releases.
