### ISSUE TITLE
Error : Illegal character in path

### ISSUE THREAD

**Issue by Rem-02** [jdneo/vscode-checkstyle#253]
**Description :**
This error appear when Checkstyle load :
`{"message":"Illegal character in path at index 20: file:/C:/Users/WIN USER/.vscode/extensions/redhat.java-0.50.0/server/../../shengchen.vscode-checkstyle-1.3.0/server/com.shengchen.checkstyle.runner-1.3.0.jar"}`

**Environment :**
OS : Windows 10
VS Code version : 1.38.1
Extension version : 1.3.0

**Comment by Vigilans** [comment]
The index 20 of this path is within your username. What is your user name here, or exactly is `WIN USER`?

**Comment by Rem-02** [comment]
Sorry, I replaced by mistake.
My user name is "progs rb".
The correct line is :
`{"message":"Illegal character in path at index 20: file:/C:/Users/progs rb/.vscode/extensions/redhat.java-0.50.0/server/../../shengchen.vscode-checkstyle-1.3.0/server/com.shengchen.checkstyle.runner-1.3.0.jar"}`
