### ISSUE TITLE
Plugin breaks checkstyle features that rely on folder structure

### ISSUE THREAD

**Issue by coryroloff** [jdneo/vscode-checkstyle#275]
Hello,

I noticed the plugin copies the Java files to a temporary folder, which is fine, except that it doesn't retain the package folder structure. This causes features in checkstyle (specifically the PackageDeclaration check and surpression regexes) to incorrectly report errors / not work.

Any chance you can update the plugin to include the package folders?

**Comment by rafaelrenanpacheco** [comment]
This causes a lot of distraction because the explorer tree gets an error color on every file of the project. I get lost on what I changed (because git also set colors on changed files), and I don't know (looking at the tree) which files actually violates some checkstyle rules.

**Comment by glide1** [comment]
I concur. The checkstyle rules for a team might defined organization wide and we might not have control over what actually goes in the rules. The plugin is really handy, but I’m beginning to ignore errors that I shouldn’t.

**Comment by jdneo** [comment]
Will release the fix in `1.5.0`
