### ISSUE TITLE
The workspace folder option should not be displayed in the case of non-multi-root

### ISSUE THREAD

**Issue by bsaby** [jdneo/vscode-checkstyle#28]
![image](https://user-images.githubusercontent.com/22470312/33818578-bcc7282e-de80-11e7-805c-0b6971ae228b.png)

**Comment by jdneo** [comment]
Please help verify in the new build, thanks.

**Comment by bsaby** [comment]
Test passed.
build used: artifacts/6/vscode-checkstyle-0.1.0.vsix
![image](https://user-images.githubusercontent.com/22470312/33822299-ff212c90-de91-11e7-83d7-7a31ed656e13.png)
