### ISSUE TITLE
Contributor guide

### ISSUE THREAD

**Issue by karlvr** [jdneo/vscode-checkstyle#287]
Hi! I'm interested in contributing some more quick fixes, but I'm struggling to get the vscode-checkstyle project up and running for development in my VS Code environment. I found a contributor guide in the previous release, but it hasn't helped me. Would it be possible to update, or perhaps to help me get set up so I can write a contributor doc?

I have opened the project in VS Code, and I've run "Launch Extension" and I have my debug VS Code window, and Checkstyle works in it. But the Java code is missing some imports (org.eclipse specifically), which it seems the plugin development environment should provide? 

npm run build-plugin succeeds. And changes I make have an effect, but it's pretty hard to work with without the dependencies loading! I've tried adding the org.eclipse.jdt.core dependency to the pom as well, but it isn't working somehow... 

Any help appreciated!

**Comment by jdneo** [comment]
Ok, I'll add a contribution guide page recently. Thank you for having the interest for contribution, Please stay in tune.

**Comment by jdneo** [comment]
@karlvr Please check https://github.com/jdneo/vscode-checkstyle/pull/288/files and let me know if it works.

Thanks.

**Comment by karlvr** [comment]
@jdneo thank you, frustratingly it still isn't behaving correctly. I've followed the steps from your guide, which is what I had done already. I have tried the Reload Target Platform step, reloading VS Code, restarting VS Code, and cleaning the Java workspace, but I still get:

> The import org.eclipse cannot be resolved.

It feels like VS Code isn't correctly loading the PDE dependencies.

The automatically created `.classpath` file in the runner project contains:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins"/>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```

I expect that `org.eclipse.pde.core.requiredPlugins` is the reference to the org.eclipse dependencies that I need?

In the sidebar under Java Projects, I see that the Plug-in Dependencies node for the runner project is empty. I wonder if I should see dependencies there?

**Comment by karlvr** [comment]
Inspecting the effective POM that the Maven for Java output refers to for the project, it contains the dependencies that we're expecting:

```
    <dependency>
      <groupId>p2.eclipse-plugin</groupId>
      <artifactId>org.eclipse.jdt.core</artifactId>
      <version>3.14.0.v20180528-0519</version>
      <scope>system</scope>
      <systemPath>/Users/karlvr/.m2/repository/p2/osgi/bundle/org.eclipse.jdt.core/3.14.0.v20180528-0519/org.eclipse.jdt.core-3.14.0.v20180528-0519.jar</systemPath>
    </dependency>
```

And that jar exists, and it contains the classes that the VS Code editor reports as missing.

I've tried uninstalling and reinstalling the `yaozheng.vscode-pde` extension. But no change yet.

**Comment by jdneo** [comment]
@karlvr Thank you for reporting this. After I cleaned my local cache, I encountered the same problem.

It turns out that the current target platform definition is out of date. I updated it in the PR. Hope the problem can be resolved now.

**Comment by karlvr** [comment]
@jdneo great, thank you. I discovered that from the Language Support for Java log but couldn't work out how to fix it! Thank you. Compiling now... Now I'll see if I can make a quick fix.

An aside, does Checkstyle really not support enforcing tab indentation?

**Comment by jdneo** [comment]
> does Checkstyle really not support enforcing tab indentation?

Sorry, could you explain more about this?

**Comment by karlvr** [comment]
@jdneo heh, it seems that to enforce space indentation there are checks in Checkstyle, but to enforce tab indentation people create regex checks, for which we can't create quick fixes.

**Comment by jdneo** [comment]
I see. Have no idea for this right now. Maybe you can ask the question in the [Checkstyle official repo](https://github.com/checkstyle/checkstyle)?
