### ISSUE TITLE
git check-ignore exec error: Error: The command line is too long.

### ISSUE THREAD

**Issue by jheidlage1222** [jdneo/vscode-checkstyle#314]
I'm getting this error in the Checkstyle output in vscode
git check-ignore exec error: Error: The command line is too long.

Setting the checkstyle.xml file or running the command to check code with checkstyle do nothing.

**Comment by jdneo** [comment]
hmmm, that's interesting, since I'm not aware of that the extension would do anything related with git.

Is there any reproduce steps? Would you mind to share a sample project?
