### ISSUE TITLE
Some checkstyle rules are not understood : MissingJavadocMethod, LineLength

### ISSUE THREAD

**Issue by lpanichi** [jdneo/vscode-checkstyle#339]
I have those errors when importing a checkstyle.xml :
```
{"message":"cannot initialize module TreeWalker - cannot initialize module MissingJavadocMethod - Unable to instantiate 'MissingJavadocMethod' class, it is also not possible to instantiate it as .MissingJavadocMethod, MissingJavadocMethodCheck, .MissingJavadocMethodCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly."}
{"message":"LineLength is not allowed as a child in Checker"}
```
What is the version of checkstyle used compatible with the extension ?
I'm using the version 1.4.1 of the extension.
VSCode 1.71.0
Java 11

The `checkstyle.xml` is working with eclipse.

**Comment by jdneo** [comment]
The checkstyle rules defined in `checkstyle.xml` can be incompatible across different checkstyle versions.

The extension uses checkstyle@8.18 by default.

You can change that by running the command `Checkstyle: Set the Checkstyle Version` and select a version which is compatible with your rules.
