### ISSUE TITLE
Question: Checkstyle tooling API vs Parsing output

### ISSUE THREAD

**Issue by sbreakey** [jdneo/vscode-checkstyle#353]
This isn't an issue, just a curiosity I have.

Looking at the implementation of this plugin, it looks pretty advanced, interacting with the Checkstyle tooling API and language server etc.

Looking at one of the other plugins, e.g. https://github.com/thomdabeast/java-checkstyle-vscode
It seems to be implemented in a much simpler, perhaps more naive, way. It basically just executes the checkstyle jar with `java -jar` and a bunch of arguments, and then parses the output to generate warnings.

Is there an inherent disadvantage to this perhaps more naive approach?

EDIT:
An advantage of the naive approach that I can see is that things like the suppressions functionality (as requested here https://github.com/jdneo/vscode-checkstyle/issues/335) would work out of the box I think.

**Comment by sbreakey** [comment]
I see this kind of thing belongs in gitter. Will move there.

**Comment by jdneo** [comment]
Moved to https://github.com/jdneo/vscode-checkstyle/issues/353, let's discuss there.
