### ISSUE TITLE
BeforeExecutionExclusionFileFilter doesn't work

### ISSUE THREAD

**Issue by Maze-fr** [jdneo/vscode-checkstyle#359]
Hello,

I specified the `BeforeExecutionExclusionFileFilter` rule to ignore test classes, like specified in the Checkstyle documentation :  
[To configure the filter to exclude all Test folder files](https://checkstyle.org/filefilters/beforeexecutionexclusionfilefilter.html#Example3-config)  

When I use the Maven plugin command line, it works.

Unfortunately, it doesn't work with VS Code plugin : I have violations on my test classes...

**Comment by jdneo** [comment]
Close due to the issue is resolved.
