### ISSUE TITLE
Can't "Launch Extension" for debugging

### ISSUE THREAD

**Issue by ItaloBorrelli** [jdneo/vscode-checkstyle#362]
### Version Info
```
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.6.7-arch1-1
```

### Reproducible Steps
1. Complete [setup steps](https://github.com/jdneo/vscode-checkstyle/blob/9714346e78e288ca0ee98b4a02dd12f9cb6b5517/CONTRIBUTING.md#setup) 1-6
2. Skip step 7 because jls seems to have an issue, but I did "right click the target.target file and select Reload Target Platform", then restart VS Code.
3. Run "Launch Extension" from debug view.

### What I expect to happen vs. What's actually happening
**Expected**: A new VS Code window should open up with the extension running. Afterwards I should be able to debug.
**Actual**: The `"preLaunchTask": "npm: watch"` seems to complete successfully and seems to be serving the webpack. No window opens.

### Console logs
I'm not sure these logs have to do with the problem, but it's possible. The issue seems to be with jls. Everything seems to build correctly even though it says `Project 'com.shengchen.checkstyle.checker' is missing required Java project: 'com.shengchen.checkstyle.runner'`

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: com.shengchen.checkstyle.runner does not exist
p @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: com.shengchen.checkstyle.runner does not exist
	at /home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1104120
	at ie (/home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1104414)
	at /home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1099198
	at Immediate.<anonymous> (/home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1099218)
	at process.processImmediate (node:internal/timers:476:21)
p @ console.ts:137
mainThreadExtensionService.ts:81 [redhat.java]com.shengchen.checkstyle.runner does not exist
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: com.shengchen.checkstyle.runner does not exist
	at /home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1104120
	at ie (/home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1104414)
	at /home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1099198
	at Immediate.<anonymous> (/home/iborrelli/.vscode/extensions/redhat.java-1.28.1-linux-x64/dist/extension.js:2:1099218)
	at process.processImmediate (node:internal/timers:476:21)
```

Thanks!

**Comment by ItaloBorrelli** [comment]
@jdneo, do you see a lot of compilation errors when you're developing the code, like `package com.puppycrawl.tools.checkstyle does not exist(compiler.err.doesnt.exist)` or do you perhaps develop the java code in eclipse?

**Comment by ItaloBorrelli** [comment]
I didn't feel like it's worth making an issue regarding it. I can take this to the discussion part of the repo as well if that's more sensible.

**Comment by jdneo** [comment]
No, I do not have such issue, I'm using VS Code.

![image](https://github.com/jdneo/vscode-checkstyle/assets/6193897/8590b3eb-9dc9-4289-951a-cd5926a20085)

Please file a discussion ticket for it.

**Comment by ItaloBorrelli** [comment]
@jdneo ended up not being a problem with the repo, but a problem with conflict between the `redhat.java` and `vscode-javac` extensions I had installed ([related](https://github.com/redhat-developer/vscode-java/issues/956)). Sorry for the trouble!
