### ISSUE TITLE
Feature Request: Please register Checkstyle for Java in the Open VSX Registry

### ISSUE THREAD

**Issue by ogiwarat** [jdneo/vscode-checkstyle#372]
I am a Java developer in Japan, and I have been using CheckStyle for almost 20 years, and I would like to continue using it in the future.

Until now, I have been using CheckStyle in Eclipse and VSCode, but for my next project, I plan to develop it with Code-OSS on [Cloud Workstation](https://cloud.google.com/workstations/docs/base-editor-overview) in Google Cloud.

However, there is no Checkstyle for Java extension in the [Open VSX Registry](https://open-vsx.org/) in the Code-OSS marketplace.

So, I have a request. Could you please register the Checkstyle for Java extension in the Open VSX Registry as well?

Thank you for such a useful extension!

**Comment by jdneo** [comment]
duplicated with https://github.com/jdneo/vscode-checkstyle/issues/286.

Currently I've no bandwidth to do/maintain it. Is it a one time work or I need to publish it to Open VSX every time?

**Comment by chromey** [comment]
@jdneo Is there any chance you would reconsider your decision? It would help Codium users a lot. It would certainly help me and my organisation. Thanks! :)
