### ISSUE TITLE
Can't set any configuration when no project opened in VSCode

### ISSUE THREAD

**Issue by bsaby** [jdneo/vscode-checkstyle#52]
1. Open VSCode
2. Install CheckStyle extension
3. Open command palatte to set any checkstyle configuration

![image](https://user-images.githubusercontent.com/22470312/34351789-b618883a-ea59-11e7-9413-f9806bdba04c.png)

**Comment by jdneo** [comment]
Hi @bsaby , the issue has been fixed.

**Comment by bsaby** [comment]
Test passed on Windows and Mac.
BUild used: number 23
