### ISSUE TITLE
The error message of checkstyle invalid version should be more accurate

### ISSUE THREAD

**Issue by bsaby** [jdneo/vscode-checkstyle#54]
Current result:
![image](https://user-images.githubusercontent.com/22470312/34351883-3fb61a12-ea5a-11e7-9f51-d21919695735.png)

**Comment by jdneo** [comment]
Hi @bsaby , the issue has been fixed.

**Comment by bsaby** [comment]
Test passed.
Build used: vscode-checkstyle-0.1.1.vsix-24
![image](https://user-images.githubusercontent.com/22470312/34397207-01a980dc-ebaf-11e7-8c80-8a4de21e44a7.png)
