### ISSUE TITLE
v0.2.0 Release End Game

### ISSUE THREAD

**Issue by jdneo** [jdneo/vscode-checkstyle#57]
## Build @jdneo

- [x] Bump version to 0.2.0
- [x] Update Readme.md
- [x] update changelog

## Test @bsaby 

- [x] Run [Test Plan](https://github.com/jdneo/vscode-checkstyle/wiki/Test-Plan)

## Release @jdneo
- [x] Add tag
- [x] Release to marketplace

**Comment by bsaby** [comment]
# Run Test Plan

1. Build: https://vscjavaci.cloudapp.net/job/vscode-checkstyle.vsix/27/Azure/
2. Test plan:  https://github.com/jdneo/vscode-checkstyle/wiki/Test-Plan
3. Test result:

Test case | Win10 x64 | Mac
-- | -- | --
Configurations | Vscode:1.19.1   JDK8 | Vscode:1.19.1   JDK8
Clean   install | Pass | Pass
Update | Pass | Pass
Uninstall | Pass | Pass
Can   set checkstyle version | Pass | Pass
Can   set checkstyle configuration | Pass | Pass
Can   turn on/off autocheck | Pass | Pass
Can   set Checkstyle property | Pass | Pass
Can   trigger checkstyle through command | Pass | Pass
Status   Bar | Pass | Pass
