### ISSUE TITLE
Output opens if there are syntax errors

### ISSUE THREAD

**Issue by keyoffecka** [jdneo/vscode-checkstyle#74]
If there are errors in the code being checked an output panel is auto opened
![output](https://image.ibb.co/gTtLZG/output.png)

This is very annoying if the 
`"checkstyle.autocheck": true`

It makes the plugin totally useless since it distracts from coding making it harder.
Without checkstyle.autocheck it also useless, in my setup the checkstyle will be anyway executed before committing the code.

Any chances to disable the Output panel auto open?

**Comment by jdneo** [comment]
Thank you for pointing out that. I agree that this is too annoying. 

I'll change the extension behavior in the next release. It will be welcomed if you would like to send out a PR for this. 😄

**Comment by jdneo** [comment]
Hi @keyoffecka , I think I have fixed this issue.

You can have a try if you want, and please let me know if this fix can satisfiy your requirements. You can do the following steps to build the extension by yourself:

1. clone the repo & go to the repo folder
2. checkout to the `develop` branch
3. run `npm install`
4. run `npm compile`
5. run `npm install -g vsce`
6. `cd client`
7. run `vsce package`

Then you can see the *.vsix file in that folder, and install this file as the extension in vscode:
![image](https://user-images.githubusercontent.com/6193897/35430566-c70a4f3a-02b3-11e8-8b30-71a9c25764c8.png)

**Comment by keyoffecka** [comment]
That worked. Thank you!
