### ISSUE TITLE
Prompt a message if an error occurs?

### ISSUE THREAD

**Issue by bsaby** [jdneo/vscode-checkstyle#78]
The current behavior is that the extension will not be forced to jump to the checkstyle output channel when an error occurs.

Enhancements:
Currently, If the checkstyle output channel is not open, prompt a message:
1. Tell user that an error occurred 
2. Provide a checkstyle output channel entry and ask the user if open it.

**Comment by jdneo** [comment]
This is a great suggestion. Let me think about how should the extension pop up the error hint.

**Comment by jdneo** [comment]
Current thinking about this:

The checkstyle status icon will have three status:
- X: has checkstyle error
- ✔️: no checkstyle error
- ⚠️: Something error occurred on checkstyle language server

**Comment by jdneo** [comment]
In #88, we change the status icon into 4 state:

- ✔️ No Checkstyle error, click it will open the output channel.
- 🐞 Has Checkstyle error, click it will open the output channel.
- ⚠️ Language server error, click it will open the output channel.
- ✏️ Wait for check, click it will trigger the command `check code with Checkstyle`.
