### ISSUE TITLE
Clicking a check icon will not open the output channel

### ISSUE THREAD

**Issue by bsaby** [jdneo/vscode-checkstyle#99]
**[Regression]** Not repro in build47

EXPECT:
A check icon will show if no checkstyle error is found, click it will open the output channel.

RESULT:
After clicking it, the icon will change to the pencil icon and then will trigger the command check code with checkstyle.

**Comment by jdneo** [comment]
Will it always checks the code or there is any specific repro steps?

**Comment by bsaby** [comment]
It always checks the code.

**Comment by jdneo** [comment]
@bsaby Thanks for report this bug!
